Fix printing of XML on parse failure
PlanetBunkum/Bunkum pull request #70
Opened 2023-11-17 02:11 UTC by Beyley

2023-11-17 22:24 UTC, jvyden requested changes
Have you checked if this also happens with JSON?

2023-11-17 22:24 UTC, jvyden commented on Bunkum.Core/Endpoints/Middlewares/MainMiddleware.cs
> +                this._logger.LogError(BunkumCategory.UserContent, $"Failed to parse object data: {e}\n\nXML: {Encoding.UTF8.GetString(body.ToArray())}");
This won't always be a MemoryStream in the future (see #67), so I'd prefer if we read everything out once at the top of the function and then used that for everything.

Might as well refactor this function while we're here

2023-11-19 21:43 UTC, jvyden approved these changes

2023-11-19 21:43 UTC, jvyden commented
Actually, before I merge, do we know if this affects performance or fixes the null byte bug?

2023-11-19 22:23 UTC, Beyley commented
> Actually, before I merge, do we know if this affects performance or fixes the null byte bug?

Performance should be exactly the same (maybe slightly faster?), and it does not fix the null byte issue, the request itself going over the wire has the null bytes, and its not just a single null byte, the game itself is reading out of bounds when sending the data

2023-11-19 22:23 UTC, merged